gui:
  mainPanelSplitMode: "flexible"
  language: "en"
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#4b5261"
  branchColors:
    "docs": blue
    "fix": red
    "feat": green
notARepository: "skip"
os:
  edit: "nvim"
update:
  days: 7
